import { ArrowRight, ArrowUpRight, Check, ChevronRight, CircleCheck, FileText, FolderOpen, LayoutDashboard, Package, Search, Settings2, ShoppingBag, Users } from "lucide-react";

const SYSTEMS = [
  { name: "CRM & follow-ups", short: "Customers", Icon: Users, title: "Keep the inquiry, quote, and follow-up in one place.", description: "A custom CRM can use your fields and sales stages, attach documents to customer records, and remind your team what needs attention. Website inquiries can enter the workflow directly.", points: ["Customer records and contact history", "Quotes and follow-up reminders", "Website forms connected to your pipeline"] },
  { name: "Orders & payments", short: "Orders", Icon: ShoppingBag, title: "Connect an approved quote to the work that follows.", description: "Create an order from a quote, connect a payment provider, and track progress through your own fulfillment stages. Build the handoffs around how your team sells and delivers.", points: ["Quote-to-order workflows", "Payment provider integrations", "Order status for your staff and customers"] },
  { name: "Products & stock", short: "Products", Icon: Package, title: "Manage the catalog behind your online store.", description: "Build a dashboard for product information, pricing, stock, and availability. Connect the systems that need those updates so your team has fewer places to enter the same data.", points: ["Product and pricing management", "Stock and availability updates", "Storefront and software connections"] },
  { name: "Customer portals", short: "Portal", Icon: FolderOpen, title: "Give customers access to the things they keep asking for.", description: "A customer portal can bring files, approvals, order updates, and messages into one place. Staff and customers get access to the screens and information their role requires.", points: ["File sharing and approvals", "Customer and staff permissions", "Project updates and account information"] },
] as const;

function DashboardScreen({ active }: { active: number }) {
  if (active === 1) return <><div className="wd-app-heading"><div><span>ORDER MANAGEMENT</span><h4>Order #1043</h4></div><span className="wd-app-badge">In progress</span></div><div className="wd-order-flow">{["Quote approved", "Payment received", "Preparing", "Complete"].map((step, i) => <div className={i < 2 ? "is-done" : ""} key={step}><span>{i < 2 ? <Check size={13} /> : i + 1}</span><p>{step}</p></div>)}</div><div className="wd-order-summary"><span>Customer</span><strong>Example customer</strong><span>Order total</span><strong>$1,250.00</strong><span>Next step</span><strong>Schedule delivery</strong></div><div className="wd-app-notice"><CircleCheck size={18} /><div><strong>Payment recorded</strong><span>Your team can see what happens next.</span></div></div></>;
  if (active === 2) return <><div className="wd-app-heading"><div><span>PRODUCT MANAGEMENT</span><h4>Product catalog</h4></div><span className="wd-app-badge">4 products</span></div><div className="wd-product-rows">{[["Amber", "Everyday collection", "$48", "24 available"], ["Sage", "Seasonal collection", "$72", "12 available"], ["Slate", "Signature collection", "$96", "8 available"], ["Sand", "Everyday collection", "$36", "Restock needed"]].map(([name, group, price, stock], i) => <div className="wd-product-row" key={name}><span className={`wd-product-swatch wd-swatch-${i}`} /><div><strong>{name}</strong><span>{group}</span></div><b>{price}</b><small>{stock}</small></div>)}</div></>;
  if (active === 3) return <><div className="wd-app-heading"><div><span>CUSTOMER WORKSPACE</span><h4>Your project</h4></div><span className="wd-app-badge">Customer view</span></div><div className="wd-portal-progress"><span>Project progress</span><b>Design review</b><div><i /></div></div><div className="wd-portal-files">{[["Project proposal.pdf", "Approved"], ["Design preview.pdf", "Ready for review"], ["Brand assets.zip", "Received"]].map(([file, status]) => <div key={file}><FileText size={23} /><span><strong>{file}</strong><small>{status}</small></span><ChevronRight size={15} /></div>)}</div><div className="wd-app-notice"><FolderOpen size={18} /><div><strong>Files and updates in one place</strong><span>Access is based on the customer’s account.</span></div></div></>;
  return <><div className="wd-app-heading"><div><span>CUSTOMER MANAGEMENT</span><h4>Sales pipeline</h4></div><span className="wd-app-badge">This week</span></div><div className="wd-pipeline">{[{name:"New inquiries",cards:["Website inquiry", "Consultation request"]},{name:"Quote sent",cards:["Service proposal", "Project estimate"]},{name:"Booked",cards:["Approved project"]}].map((column, i) => <div className="wd-pipeline-col" key={column.name}><h5><i />{column.name}<span>{column.cards.length}</span></h5>{column.cards.map((card, j) => <div className="wd-pipeline-card" key={card}><span className="wd-pipeline-avatar">{i === 2 ? <Check size={13} /> : <Users size={12} />}</span><strong>{card}</strong><p>{i === 0 ? "From your website" : "Example customer"}</p><div><span>{i === 2 ? "Deposit paid" : j === 0 ? "Follow up today" : "Ready to review"}</span><ArrowUpRight size={12} /></div></div>)}</div>)}</div><div className="wd-app-notice"><CircleCheck size={18} /><div><strong>New inquiry captured</strong><span>Contact details, source, and next action—together.</span></div></div></>;
}

export default function BusinessSystems() {
  return <section className="wd-section wd-systems" id="custom-systems" aria-labelledby="systems-heading"><div className="wd-container">
    <div className="wd-section-heading"><div><p className="wd-eyebrow">Custom backends / Connected operations</p><h2 id="systems-heading">The website is only<br />part of what we build.</h2></div><p>Customer portals, CRMs, order management, and integrations—built around the way your business operates.</p></div>
    <div className="wd-system-list">
      {SYSTEMS.map((system, index) => (
        <article className="wd-system-detail" key={system.name} aria-labelledby={"system-" + index + "-heading"}>
          <div className="wd-system-copy"><span className="wd-eyebrow wd-system-label"><system.Icon size={20} />0{index + 1} / {system.name}</span><h3 id={"system-" + index + "-heading"}>{system.title}</h3><p>{system.description}</p><ul>{system.points.map(point => <li key={point}><Check size={16} />{point}</li>)}</ul></div>
          <figure className="wd-system-figure"><div className="wd-app-window" aria-hidden="true"><div className="wd-app-chrome"><span><i /><i /><i /></span><span>YOUR BUSINESS / WORKSPACE</span><Settings2 size={13} /></div><div className="wd-app-body"><div className="wd-app-sidebar"><b>YOUR<br />BUSINESS<span>WORKSPACE</span></b>{SYSTEMS.map(({short,Icon},i)=><div className={i===index?"is-active":""} key={short}><Icon size={15} /><span>{short}</span></div>)}<div><LayoutDashboard size={15}/><span>Reports</span></div><small>Sample workspace</small></div><div className="wd-app-main"><div className="wd-app-toolbar"><span><Search size={13}/> Search your workspace</span><span>JD</span></div><DashboardScreen active={index}/></div></div></div><figcaption>{system.name} — example interface with illustrative data. Your system would be scoped and designed for your business.</figcaption></figure>
        </article>
      ))}
    </div>
    <div className="wd-systems-cost"><span className="wd-eyebrow">Review your existing tools</span><p>Already paying for several subscriptions? We can compare what to keep, what to connect, and what a custom system could replace—including development, hosting, and maintenance costs.</p><a href="#start">Review my setup <ArrowRight size={17}/></a></div>
  </div></section>;
}
