import { ArrowRight, ArrowUpRight, Check, ChevronRight, CircleCheck, FileText, FolderOpen, LayoutDashboard, Package, Search, Settings2, ShoppingBag, Users } from "lucide-react";

const SYSTEMS = [
  { name: "Inquiries & follow-ups", short: "Customers", Icon: Users, title: "Spend less time moving leads between tools.", description: "An inquiry can arrive in your dashboard with the customer’s details and a next step already attached. Your team can follow up from one record instead of rebuilding the same information in a spreadsheet and a separate CRM.", points: ["Less copying from forms into spreadsheets", "Follow-ups with a clear owner and due date", "Customer history available to the whole team"] },
  { name: "Orders & payments", short: "Orders", Icon: ShoppingBag, title: "Use the quote details again when the job starts.", description: "An approved quote can become an order without someone typing it all out again. Connect your payment provider and show the order’s next step, so staff spend less time checking different systems for updates.", points: ["Fewer repeated entries between sales and delivery", "Payment and order status in one view", "Less back-and-forth about what happens next"] },
  { name: "Products & stock", short: "Products", Icon: Package, title: "Update a product once, instead of in three places.", description: "A connected dashboard can share product, pricing, and stock changes with your online store and other tools. That can reduce routine admin and the mistakes that come from maintaining separate lists.", points: ["Fewer manual catalog updates", "Less time reconciling different stock records", "Clear visibility when an item needs attention"] },
  { name: "Customer portals", short: "Portal", Icon: FolderOpen, title: "Answer routine questions without another email.", description: "Give customers a secure place to find their files, review work, and check progress. They can get an update when they need it, while your team spends less time resending documents and answering the same status questions.", points: ["Fewer requests for files and progress updates", "Approvals kept with the relevant project", "Access limited to each customer’s account"] },
] as const;

function DashboardScreen({ active }: { active: number }) {
  if (active === 1) return <><div className="wd-app-heading"><div><span>ORDER MANAGEMENT</span><h4>Order #1043</h4></div><span className="wd-app-badge">In progress</span></div><div className="wd-order-flow">{["Quote approved", "Payment received", "Preparing", "Complete"].map((step, i) => <div className={i < 2 ? "is-done" : ""} key={step}><span>{i < 2 ? <Check size={13} /> : i + 1}</span><p>{step}</p></div>)}</div><div className="wd-order-summary"><span>Customer</span><strong>Example customer</strong><span>Order total</span><strong>$1,250.00</strong><span>Next step</span><strong>Schedule delivery</strong></div><div className="wd-app-notice"><CircleCheck size={18} /><div><strong>Payment recorded</strong><span>Your team can see what happens next.</span></div></div></>;
  if (active === 2) return <><div className="wd-app-heading"><div><span>PRODUCT MANAGEMENT</span><h4>Product catalog</h4></div><span className="wd-app-badge">4 products</span></div><div className="wd-product-rows">{[["Amber", "Everyday collection", "$48", "24 available"], ["Sage", "Seasonal collection", "$72", "12 available"], ["Slate", "Signature collection", "$96", "8 available"], ["Sand", "Everyday collection", "$36", "Restock needed"]].map(([name, group, price, stock], i) => <div className="wd-product-row" key={name}><span className={`wd-product-swatch wd-swatch-${i}`} /><div><strong>{name}</strong><span>{group}</span></div><b>{price}</b><small>{stock}</small></div>)}</div></>;
  if (active === 3) return <><div className="wd-app-heading"><div><span>CUSTOMER WORKSPACE</span><h4>Your project</h4></div><span className="wd-app-badge">Customer view</span></div><div className="wd-portal-progress"><span>Project progress</span><b>Design review</b><div><i /></div></div><div className="wd-portal-files">{[["Project proposal.pdf", "Approved"], ["Design preview.pdf", "Ready for review"], ["Brand assets.zip", "Received"]].map(([file, status]) => <div key={file}><FileText size={23} /><span><strong>{file}</strong><small>{status}</small></span><ChevronRight size={15} /></div>)}</div><div className="wd-app-notice"><FolderOpen size={18} /><div><strong>Files and updates in one place</strong><span>Access is based on the customer’s account.</span></div></div></>;
  return <><div className="wd-app-heading"><div><span>CUSTOMER MANAGEMENT</span><h4>Sales pipeline</h4></div><span className="wd-app-badge">This week</span></div><div className="wd-pipeline">{[{name:"New inquiries",cards:["Website inquiry", "Consultation request"]},{name:"Quote sent",cards:["Service proposal", "Project estimate"]},{name:"Booked",cards:["Approved project"]}].map((column, i) => <div className="wd-pipeline-col" key={column.name}><h5><i />{column.name}<span>{column.cards.length}</span></h5>{column.cards.map((card, j) => <div className="wd-pipeline-card" key={card}><span className="wd-pipeline-avatar">{i === 2 ? <Check size={13} /> : <Users size={12} />}</span><strong>{card}</strong><p>{i === 0 ? "From your website" : "Example customer"}</p><div><span>{i === 2 ? "Deposit paid" : j === 0 ? "Follow up today" : "Ready to review"}</span><ArrowUpRight size={12} /></div></div>)}</div>)}</div><div className="wd-app-notice"><CircleCheck size={18} /><div><strong>New inquiry captured</strong><span>Contact details, source, and next action—together.</span></div></div></>;
}

export default function BusinessSystems() {
  return <section className="wd-section wd-systems" id="custom-systems" aria-labelledby="systems-heading"><div className="wd-container">
    <div className="wd-section-heading" data-entrance="rise"><div><p className="wd-eyebrow">Custom dashboards & business tools</p><h2 id="systems-heading">Where a custom system<br />can save you money.</h2></div><p>Monthly subscriptions add up. So does time spent entering the same information twice. A custom dashboard can connect that work and replace tools you no longer need.</p></div>
    <div className="wd-cost-story" data-entrance="card">
      <div className="wd-cost-example"><span className="wd-eyebrow">Illustrative software costs</span><div className="wd-cost-equation"><span><strong>$300</strong><small>per month in subscriptions</small></span><ArrowRight size={27} /><span><strong>$10,800</strong><small>over three years</small></span></div><p>Example: $300 × 36 months in subscription fees. Compare this with the full cost of a custom build to see whether it would save you money.</p></div>
      <div className="wd-cost-explanation"><h3>Work out what is worth replacing.</h3><p>We identify subscriptions you could replace and repetitive work you could reduce. Then we compare those benefits with development, migration, hosting, support, and any services you still need.</p><p>The goal is fewer avoidable costs and more time for your team. If an existing tool is the better fit, we can connect it instead of rebuilding it.</p></div>
    </div>
    <div className="wd-system-list">
      {SYSTEMS.map((system, index) => (
        <article className="wd-system-detail" key={system.name} aria-labelledby={"system-" + index + "-heading"}>
          <div className="wd-system-copy" data-entrance="rise"><span className="wd-eyebrow wd-system-label"><system.Icon size={20} />0{index + 1} / {system.name}</span><h3 id={"system-" + index + "-heading"}>{system.title}</h3><p>{system.description}</p><ul>{system.points.map(point => <li key={point}><Check size={16} />{point}</li>)}</ul></div>
          <figure className="wd-system-figure" data-entrance="screen" data-entrance-delay="1"><div className="wd-app-window" aria-hidden="true"><div className="wd-app-chrome"><span><i /><i /><i /></span><span>YOUR BUSINESS / WORKSPACE</span><Settings2 size={13} /></div><div className="wd-app-body"><div className="wd-app-sidebar"><b>YOUR<br />BUSINESS<span>WORKSPACE</span></b>{SYSTEMS.map(({short,Icon},i)=><div className={i===index?"is-active":""} key={short}><Icon size={15} /><span>{short}</span></div>)}<div><LayoutDashboard size={15}/><span>Reports</span></div><small>Sample workspace</small></div><div className="wd-app-main"><div className="wd-app-toolbar"><span><Search size={13}/> Search your workspace</span><span>JD</span></div><DashboardScreen active={index}/></div></div></div><figcaption>{system.name} — example interface with illustrative data. Your system would be scoped and designed for your business.</figcaption></figure>
        </article>
      ))}
    </div>
    <div className="wd-systems-cost" data-entrance="unfold"><span className="wd-eyebrow">Make the numbers work first</span><p>Tell us which tools you pay for and where your team loses time. We’ll discuss what could be connected or replaced, then scope a build you can compare against the cost of staying as you are.</p><a href="#start">Discuss my software costs <ArrowRight size={17}/></a></div>
  </div></section>;
}
